file(READ "${CMAKE_CURRENT_LIST_DIR}/../source/dependencies.lock.json" PCAD_DEPENDENCIES)
function(pcad_extract name result)
  string(JSON archive GET "${PCAD_DEPENDENCIES}" ${name} archive)
  string(JSON expected GET "${PCAD_DEPENDENCIES}" ${name} sha256)
  string(JSON root GET "${PCAD_DEPENDENCIES}" ${name} root)
  set(input "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../source/${archive}")
  file(SHA256 "${input}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Upstream archive hash mismatch: ${name}")
  endif()
  set(destination "${CMAKE_BINARY_DIR}/_deps/${name}-${actual}")
  if(NOT EXISTS "${destination}/ready")
    file(MAKE_DIRECTORY "${destination}")
    file(ARCHIVE_EXTRACT INPUT "${input}" DESTINATION "${destination}")
    file(WRITE "${destination}/ready" "${actual}")
  endif()
  set(${result} "${destination}/${root}" PARENT_SCOPE)
endfunction()
pcad_extract(sqlite PCAD_SQLITE)
pcad_extract(xz PCAD_XZ)
pcad_extract(zlib PCAD_ZLIB)
pcad_extract(olc PCAD_OLC)
pcad_extract(json PCAD_JSON)

set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(ZLIB_BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(ZLIB_BUILD_SHARED OFF CACHE BOOL "" FORCE)
set(ZLIB_BUILD_STATIC ON CACHE BOOL "" FORCE)
add_subdirectory("${PCAD_ZLIB}" "${CMAKE_BINARY_DIR}/_deps/zlib-build" EXCLUDE_FROM_ALL)
set(XZ_TOOL_XZ OFF CACHE BOOL "" FORCE)
set(XZ_TOOL_XZDEC OFF CACHE BOOL "" FORCE)
set(XZ_TOOL_LZMADEC OFF CACHE BOOL "" FORCE)
set(XZ_TOOL_LZMAINFO OFF CACHE BOOL "" FORCE)
set(XZ_TOOL_SCRIPTS OFF CACHE BOOL "" FORCE)
set(XZ_DOC OFF CACHE BOOL "" FORCE)
set(ENABLE_NLS OFF CACHE BOOL "" FORCE)
add_subdirectory("${PCAD_XZ}" "${CMAKE_BINARY_DIR}/_deps/xz-build" EXCLUDE_FROM_ALL)
add_library(pcad_sqlite STATIC "${PCAD_SQLITE}/sqlite3.c")
target_include_directories(pcad_sqlite PUBLIC "${PCAD_SQLITE}")
target_compile_definitions(pcad_sqlite PRIVATE SQLITE_THREADSAFE=1 SQLITE_OMIT_LOAD_EXTENSION SQLITE_DQS=0 SQLITE_DEFAULT_MEMSTATUS=0 SQLITE_ENABLE_API_ARMOR)
# The pinned upstream encoder maps exactly -180 degrees to +180 when lng == 0.
# Preserve the original archive and build a narrowly corrected local copy.
file(READ "${PCAD_OLC}/cpp/openlocationcode.cc" PCAD_OLC_SOURCE)
string(FIND "${PCAD_OLC_SOURCE}" "if (lng <= 0)" PCAD_OLC_FIX_POSITION)
if(PCAD_OLC_FIX_POSITION EQUAL -1)
  message(FATAL_ERROR "Pinned OLC longitude correction no longer applies")
endif()
string(REPLACE "if (lng <= 0)" "if (lng < 0)" PCAD_OLC_SOURCE "${PCAD_OLC_SOURCE}")
# Match the reference Python's shifted-coordinate rounding at exact grid edges.
foreach(axis lat lng)
  if(axis STREQUAL "lat")
    set(coordinate latitude)
    set(bound Latitude)
    set(precision Lat)
  else()
    set(coordinate longitude)
    set(bound Longitude)
    set(precision Lng)
  endif()
  set(before "int64_t ${axis} = floor(${coordinate} * kGrid${precision}PrecisionInverse);\n  ${axis} += k${bound}MaxDegrees * kGrid${precision}PrecisionInverse;")
  string(FIND "${PCAD_OLC_SOURCE}" "${before}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "Pinned OLC rounding correction no longer applies")
  endif()
  string(REPLACE "${before}" "int64_t ${axis} = pcad_olc_quantize((${coordinate} + k${bound}MaxDegrees) * kGrid${precision}PrecisionInverse);" PCAD_OLC_SOURCE "${PCAD_OLC_SOURCE}")
endforeach()
string(PREPEND PCAD_OLC_SOURCE "#include \"olc_quantize.hpp\"\n")
file(CONFIGURE OUTPUT "${CMAKE_BINARY_DIR}/_deps/olc-corrected.cc" CONTENT "${PCAD_OLC_SOURCE}" @ONLY)
add_library(pcad_olc STATIC "${CMAKE_BINARY_DIR}/_deps/olc-corrected.cc" "${PCAD_OLC}/cpp/codearea.cc")
target_include_directories(pcad_olc PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src")
target_include_directories(pcad_olc PUBLIC "${PCAD_OLC}/cpp")
